-- MySQL Script generated by MySQL Workbench
-- Tue Jan 19 01:59:23 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema artcurator
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `artcurator` ;

-- -----------------------------------------------------
-- Schema artcurator
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artcurator` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `artcurator` ;

-- -----------------------------------------------------
-- Table `artcurator`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`address` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`address` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `apartment` VARCHAR(75) NOT NULL,
  `city` VARCHAR(75) NOT NULL,
  `country` VARCHAR(75) NOT NULL,
  `pin` VARCHAR(6) NOT NULL,
  `state` VARCHAR(75) NOT NULL,
  `street` VARCHAR(75) NOT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKda8tuywtf0gb6sedwk7la1pgi` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKda8tuywtf0gb6sedwk7la1pgi`
    FOREIGN KEY (`user_id`)
    REFERENCES `artcurator`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artcurator`.`cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`cart` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`cart` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `art_name` VARCHAR(75) NULL DEFAULT NULL,
  `artist_name` VARCHAR(75) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKl70asp4l4w0jmbm1tqyofho4o` (`user_id` ASC) VISIBLE,
  INDEX `FK3d704slv66tw6x5hmbm6p2x3u` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK3d704slv66tw6x5hmbm6p2x3u`
    FOREIGN KEY (`product_id`)
    REFERENCES `artcurator`.`product` (`id`),
  CONSTRAINT `FKl70asp4l4w0jmbm1tqyofho4o`
    FOREIGN KEY (`user_id`)
    REFERENCES `artcurator`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artcurator`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`orders` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`orders` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `order_id` BIGINT(20) NULL DEFAULT NULL,
  `order_time` DATETIME NULL DEFAULT NULL,
  `product_id` BIGINT(20) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK787ibr3guwp6xobrpbofnv7le` (`product_id` ASC) VISIBLE,
  INDEX `FKel9kyl84ego2otj2accfd8mr7` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK787ibr3guwp6xobrpbofnv7le`
    FOREIGN KEY (`product_id`)
    REFERENCES `artcurator`.`product` (`id`),
  CONSTRAINT `FKel9kyl84ego2otj2accfd8mr7`
    FOREIGN KEY (`user_id`)
    REFERENCES `artcurator`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artcurator`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`product` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`product` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `artist` VARCHAR(75) NOT NULL,
  `category` VARCHAR(75) NOT NULL,
  `description` VARCHAR(75) NULL DEFAULT NULL,
  `image` LONGBLOB NULL DEFAULT NULL,
  `image_type` VARCHAR(75) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  `seller_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmsvavr0t3lra70gf2ymxdi5te` (`seller_id` ASC) VISIBLE,
  CONSTRAINT `FKmsvavr0t3lra70gf2ymxdi5te`
    FOREIGN KEY (`seller_id`)
    REFERENCES `artcurator`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artcurator`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`user` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `dob` DATE NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `name` VARCHAR(75) NOT NULL,
  `password` VARCHAR(75) NOT NULL,
  `phone` VARCHAR(11) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `wallet_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  INDEX `FKposytpmub7fhua33j3ts2jot6` (`wallet_id` ASC) VISIBLE,
  CONSTRAINT `FKposytpmub7fhua33j3ts2jot6`
    FOREIGN KEY (`wallet_id`)
    REFERENCES `artcurator`.`wallet` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artcurator`.`wallet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `artcurator`.`wallet` ;

CREATE TABLE IF NOT EXISTS `artcurator`.`wallet` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
